#!/bin/sh
# Zabbix server entrypoint [FR4.2][BR4.1][functional-spec.md ワークフロー3].
#
# Reads the same environment variable names as the official zabbix/zabbix-server-mysql image
# (DB_SERVER_HOST, DB_SERVER_PORT, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE), generates
# /etc/zabbix/zabbix_server.conf from them, then runs zabbix_server in the foreground.
# LogType=console sends all logging to stdout/stderr instead of a log file [observability-design.md].

set -eu

CONFIG_FILE="/etc/zabbix/zabbix_server.conf"

: "${DB_SERVER_HOST:=mysql-server}"
: "${DB_SERVER_PORT:=3306}"
: "${MYSQL_USER:=zabbix}"
: "${MYSQL_DATABASE:=zabbix}"

fail() {
	echo "**** ERROR: $1" >&2
	echo "**** Exiting..." >&2
	exit 1
}

if [ -z "${MYSQL_PASSWORD:-}" ]; then
	fail "MYSQL_PASSWORD is not set. This variable is mandatory for Zabbix server to connect to the database."
fi

# build-and-test: this connector never skips certificate verification (see the DBTLSConnect note below),
# so a self-signed target (this project's own dev-mysql, or any MySQL an operator hasn't given a
# CA-signed cert) can only be reached by making the OS trust that specific certificate, not by
# configuring Zabbix. TRUST_DB_CA_FILE (a path this container can read, e.g. a read-only mount of
# dev-mysql's data volume) is this project's own convenience variable for that — not part of the
# official zabbix/zabbix-server-mysql image. Needs root, which is why this container does not drop to
# the zabbix user until after this step (see the su-exec exec below).
if [ -n "${TRUST_DB_CA_FILE:-}" ] && [ -f "${TRUST_DB_CA_FILE}" ]; then
	echo "**** Trusting DB server CA certificate from ${TRUST_DB_CA_FILE}..."
	cp "${TRUST_DB_CA_FILE}" /usr/local/share/ca-certificates/db-server-ca.crt
	update-ca-certificates
fi

echo "**** Generating ${CONFIG_FILE} from environment variables..."

cat > "${CONFIG_FILE}" <<CONF
# Generated by docker/server/entrypoint.sh at container start — do not edit by hand, it is overwritten on
# every restart.

LogType=console
PidFile=/run/zabbix/zabbix_server.pid
SocketDir=/run/zabbix

DBHost=${DB_SERVER_HOST}
DBPort=${DB_SERVER_PORT}
DBName=${MYSQL_DATABASE}
DBUser=${MYSQL_USER}
DBPassword=${MYSQL_PASSWORD}

AlertScriptsPath=/var/lib/zabbix/alertscripts
ExternalScripts=/var/lib/zabbix/externalscripts
LoadModulePath=/var/lib/zabbix/modules
ExportDir=/var/lib/zabbix/export
CONF

# build-and-test found a known limitation with this image's mariadb-connector-c: it never skips
# certificate verification, for ANY DBTLSConnect value ("verify_ca" is rejected outright as unsupported
# for a MariaDB-linked build — src/libs/zbxdbhigh/db.c — and "required" still verifies). It can
# therefore only reach a MySQL whose certificate the system CA bundle already trusts; a self-signed
# cert (e.g. MySQL 8.x's own auto-generated default, or this project's dev-mysql) fails either way —
# "self-signed certificate in certificate chain" with TLS available, "SSL is required, but the server
# does not support it" if the target has no TLS at all. NFR1.3's "same-trusted-network, TLS not needed"
# assumption does not hold for this connector regardless of network trust; see test-results.md for the
# full investigation. Left unset (the default), no DBTLSConnect line is generated at all. Setting
# ZBX_DBTLSCONNECT=required (matching the official zabbix/zabbix-server-mysql image's env var name
# [BR4.1]) is exposed here for a production MySQL whose certificate IS already trusted.
if [ -n "${ZBX_DBTLSCONNECT:-}" ]; then
	{
		echo ""
		echo "DBTLSConnect=${ZBX_DBTLSCONNECT}"
		[ -n "${ZBX_DBTLSCAFILE:-}" ] && echo "DBTLSCAFile=${ZBX_DBTLSCAFILE}"
		[ -n "${ZBX_DBTLSCERTFILE:-}" ] && echo "DBTLSCertFile=${ZBX_DBTLSCERTFILE}"
		[ -n "${ZBX_DBTLSKEYFILE:-}" ] && echo "DBTLSKeyFile=${ZBX_DBTLSKEYFILE}"
	} >> "${CONFIG_FILE}"
fi

echo "**** Starting Zabbix server..."
exec su-exec zabbix zabbix_server --foreground -c "${CONFIG_FILE}"
