#!/bin/sh
# Zabbix agent2 entrypoint [FR5.2][BR4.1][functional-spec.md ワークフロー3].
#
# Reads environment variables matching the official zabbix/zabbix-agent2 image naming convention
# (ZBX_SERVER_HOST, ZBX_HOSTNAME), generates /etc/zabbix/zabbix_agent2.conf, then runs zabbix_agent2 in
# the foreground. LogType=console sends all logging to stdout/stderr instead of a log file
# [observability-design.md].

set -eu

CONFIG_FILE="/etc/zabbix/zabbix_agent2.conf"

: "${ZBX_SERVER_HOST:=zabbix-server}"

echo "**** Generating ${CONFIG_FILE} from environment variables..."

{
	echo "# Generated by docker/agent2/entrypoint.sh at container start — do not edit by hand, it is"
	echo "# overwritten on every restart."
	echo ""
	echo "LogType=console"
	echo "PidFile=/run/zabbix/zabbix_agent2.pid"
	echo "ControlSocket=/run/zabbix/agent.sock"
	echo ""
	echo "Server=${ZBX_SERVER_HOST}"
	echo "ServerActive=${ZBX_SERVER_HOST}"
	echo ""
	if [ -n "${ZBX_HOSTNAME:-}" ]; then
		echo "Hostname=${ZBX_HOSTNAME}"
	fi
	echo "EnablePersistentBuffer=0"
} > "${CONFIG_FILE}"

echo "**** Starting Zabbix agent2..."
exec zabbix_agent2 --foreground -c "${CONFIG_FILE}"
