#!/bin/sh
# Zabbix proxy (SQLite3) entrypoint.
#
# Takes the environment variables of the official zabbix/zabbix-proxy-sqlite3 image, generates
# /etc/zabbix/zabbix_proxy.conf from them and runs zabbix_proxy in the foreground. As in the official
# image, a variable that is unset or empty leaves its parameter at Zabbix's default. LogType=console sends
# all logging to stdout/stderr instead of a log file, matching server/agent2's entrypoints.
#
# Supported: the scalar parameters in SCALARS below, Hostname/HostnameItem, ZBX_USE_NODE_NAME_AS_DB_NAME,
# the TLS parameters (including TLS material given as a plain value, see tls_file) and ZBX_LOADMODULE.
# Not supported, because this image is built without the feature or has no volume for it: the Java gateway,
# IPMI, SNMP traps, SSH and fping variables. Any other ZBX_* variable that is set is reported with a warning
# at start, so a setting is never ignored silently (a dropped ZBX_TLSCONNECT would otherwise mean an
# unencrypted link to the server).

set -eu

CONFIG_FILE="/etc/zabbix/zabbix_proxy.conf"
HOME_DIR="/var/lib/zabbix"
ENC_DIR="${HOME_DIR}/enc"
INTERNAL_ENC_DIR="${HOME_DIR}/enc_internal"
NL='
'

# <official variable>:<zabbix_proxy.conf parameter>
SCALARS="
ZBX_PROXYMODE:ProxyMode
ZBX_LISTENIP:ListenIP
ZBX_LISTENPORT:ListenPort
ZBX_LISTENBACKLOG:ListenBacklog
ZBX_SOURCEIP:SourceIP
ZBX_DEBUGLEVEL:DebugLevel
ZBX_ENABLEREMOTECOMMANDS:EnableRemoteCommands
ZBX_LOGREMOTECOMMANDS:LogRemoteCommands
ZBX_PROXYLOCALBUFFER:ProxyLocalBuffer
ZBX_PROXYOFFLINEBUFFER:ProxyOfflineBuffer
ZBX_PROXYHEARTBEATFREQUENCY:HeartbeatFrequency
ZBX_CONFIGFREQUENCY:ConfigFrequency
ZBX_DATASENDERFREQUENCY:DataSenderFrequency
ZBX_STATSALLOWEDIP:StatsAllowedIP
ZBX_STARTPREPROCESSORS:StartPreprocessors
ZBX_STARTPOLLERS:StartPollers
ZBX_STARTPOLLERSUNREACHABLE:StartPollersUnreachable
ZBX_STARTTRAPPERS:StartTrappers
ZBX_STARTPINGERS:StartPingers
ZBX_STARTDISCOVERERS:StartDiscoverers
ZBX_STARTHTTPPOLLERS:StartHTTPPollers
ZBX_STARTVMWARECOLLECTORS:StartVMwareCollectors
ZBX_VMWAREFREQUENCY:VMwareFrequency
ZBX_VMWAREPERFFREQUENCY:VMwarePerfFrequency
ZBX_VMWARECACHESIZE:VMwareCacheSize
ZBX_VMWARETIMEOUT:VMwareTimeout
ZBX_HOUSEKEEPINGFREQUENCY:HousekeepingFrequency
ZBX_CACHESIZE:CacheSize
ZBX_STARTDBSYNCERS:StartDBSyncers
ZBX_HISTORYCACHESIZE:HistoryCacheSize
ZBX_HISTORYINDEXCACHESIZE:HistoryIndexCacheSize
ZBX_TIMEOUT:Timeout
ZBX_TRAPPERTIMEOUT:TrapperTimeout
ZBX_UNREACHABLEPERIOD:UnreachablePeriod
ZBX_UNAVAILABLEDELAY:UnavailableDelay
ZBX_UNREACHABLEDELAY:UnreachableDelay
ZBX_LOGSLOWQUERIES:LogSlowQueries
ZBX_TLSCONNECT:TLSConnect
ZBX_TLSACCEPT:TLSAccept
ZBX_TLSSERVERCERTISSUER:TLSServerCertIssuer
ZBX_TLSSERVERCERTSUBJECT:TLSServerCertSubject
ZBX_TLSCIPHERALL:TLSCipherAll
ZBX_TLSCIPHERALL13:TLSCipherAll13
ZBX_TLSCIPHERCERT:TLSCipherCert
ZBX_TLSCIPHERCERT13:TLSCipherCert13
ZBX_TLSCIPHERPSK:TLSCipherPSK
ZBX_TLSCIPHERPSK13:TLSCipherPSK13
ZBX_TLSPSKIDENTITY:TLSPSKIdentity
"

# <conf parameter>:<variable holding a path>:<variable holding the content itself>
TLS_FILES="
TLSCAFile:ZBX_TLSCAFILE:ZBX_TLSCA
TLSCRLFile:ZBX_TLSCRLFILE:ZBX_TLSCRL
TLSCertFile:ZBX_TLSCERTFILE:ZBX_TLSCERT
TLSKeyFile:ZBX_TLSKEYFILE:ZBX_TLSKEY
TLSPSKFile:ZBX_TLSPSKFILE:ZBX_TLSPSK
"

fail() {
	echo "**** ERROR: $1" >&2
	echo "**** Exiting..." >&2
	exit 1
}

zbx_env_names() {
	env | sed -n 's/^\(ZBX_[A-Za-z0-9_]*\)=.*/\1/p'
}

# conf_set <parameter> <value> — appends the parameter unless the value is empty.
conf_set() {
	[ -n "$2" ] || return 0
	case "$2" in
		*"${NL}"*) fail "the value for $1 contains a line break" ;;
	esac
	printf '%s=%s\n' "$1" "$2" >> "${CONFIG_FILE}"
}

env_value() {
	printenv "$1" || true
}

# tls_file <parameter> <path variable> <content variable> — a value in the content variable is written to a
# file under enc_internal and wins; otherwise the path variable is used, a relative path being looked up in
# the enc volume. Mirrors the official image.
tls_file() {
	file="$(env_value "$2")"
	content="$(env_value "$3")"
	if [ -n "${content}" ]; then
		file="${INTERNAL_ENC_DIR}/$1"
		( umask 077 && printf '%s\n' "${content}" > "${file}" )
	elif [ -n "${file}" ]; then
		case "${file}" in
			/*) ;;
			*) file="${ENC_DIR}/${file}" ;;
		esac
	fi
	conf_set "$1" "${file}"
}

: "${ZBX_SERVER_HOST:=zabbix-server}"
: "${ZBX_SERVER_PORT:=10051}"
hostname_default="zabbix-proxy-sqlite3"

echo "**** Generating ${CONFIG_FILE} from environment variables..."

cat > "${CONFIG_FILE}" <<'CONF'
# Generated by docker/proxy/entrypoint.sh at container start — do not edit by hand, it is
# overwritten on every restart.

LogType=console
PidFile=/run/zabbix/zabbix_proxy.pid
SocketDir=/run/zabbix
ExternalScripts=/var/lib/zabbix/externalscripts
CONF

conf_set Server "${ZBX_SERVER_HOST}"
conf_set ServerPort "${ZBX_SERVER_PORT}"

if [ -z "${ZBX_HOSTNAME:-}" ] && [ -n "${ZBX_HOSTNAMEITEM:-}" ]; then
	conf_set HostnameItem "${ZBX_HOSTNAMEITEM}"
else
	conf_set Hostname "${ZBX_HOSTNAME:-${hostname_default}}"
	conf_set HostnameItem "${ZBX_HOSTNAMEITEM:-}"
fi

# The one piece of local state this component owns (see docker/proxy/Dockerfile): a SQLite file under the
# db_data volume, named after the proxy's Hostname so several proxies can share one image without colliding
# on one file — or after the container's own host name with ZBX_USE_NODE_NAME_AS_DB_NAME=true.
if [ "$(env_value ZBX_USE_NODE_NAME_AS_DB_NAME | tr '[:upper:]' '[:lower:]')" = "true" ]; then
	db_name="$(uname -n)"
else
	db_name="${ZBX_HOSTNAME:-${hostname_default}}"
fi
case "${db_name}" in
	*/*) fail "ZBX_HOSTNAME must not contain a '/' (it names the SQLite file)" ;;
esac
conf_set DBName "${HOME_DIR}/db_data/${db_name}.sqlite"

for pair in ${SCALARS}; do
	conf_set "${pair#*:}" "$(env_value "${pair%%:*}")"
done

for entry in ${TLS_FILES}; do
	key="${entry%%:*}"
	rest="${entry#*:}"
	tls_file "${key}" "${rest%%:*}" "${rest#*:}"
done

if [ -n "$(env_value ZBX_LOADMODULE)" ]; then
	conf_set LoadModulePath "${HOME_DIR}/modules"
	old_ifs="${IFS}"
	IFS=','
	for module in $(env_value ZBX_LOADMODULE); do
		conf_set LoadModule "${module}"
	done
	IFS="${old_ifs}"
fi

# Tell the operator about anything set that this image does not act on.
known=" ZBX_SERVER_HOST ZBX_SERVER_PORT ZBX_HOSTNAME ZBX_HOSTNAMEITEM ZBX_USE_NODE_NAME_AS_DB_NAME ZBX_LOADMODULE ZBX_CLEAR_ENV"
for pair in ${SCALARS}; do
	known="${known} ${pair%%:*}"
done
for entry in ${TLS_FILES}; do
	rest="${entry#*:}"
	known="${known} ${rest%%:*} ${rest#*:}"
done
for name in $(zbx_env_names); do
	case "${known} " in
		*" ${name} "*) ;;
		*) echo "**** WARNING: ${name} is set but is not supported by this image; it is ignored." >&2 ;;
	esac
done

# As in the official image, drop ZBX_* from the environment zabbix_proxy runs with (it may hold PSK/key
# material); ZBX_CLEAR_ENV=false keeps them.
if [ "${ZBX_CLEAR_ENV:-true}" != "false" ]; then
	for name in $(zbx_env_names); do
		unset "${name}"
	done
fi

echo "**** Starting Zabbix proxy..."
exec zabbix_proxy --foreground -c "${CONFIG_FILE}"
