#!/bin/sh
# Zabbix proxy (SQLite3) entrypoint.
#
# Reads environment variables matching the official zabbix/zabbix-proxy-sqlite3 image naming
# convention (ZBX_SERVER_HOST, ZBX_SERVER_PORT, ZBX_HOSTNAME), generates /etc/zabbix/zabbix_proxy.conf,
# then runs zabbix_proxy in the foreground. LogType=console sends all logging to stdout/stderr instead
# of a log file, matching server/agent2's own entrypoints.

set -eu

CONFIG_FILE="/etc/zabbix/zabbix_proxy.conf"

: "${ZBX_SERVER_HOST:=zabbix-server}"
: "${ZBX_SERVER_PORT:=10051}"
: "${ZBX_HOSTNAME:=zabbix-proxy-sqlite3}"

echo "**** Generating ${CONFIG_FILE} from environment variables..."

{
	echo "# Generated by docker/proxy/entrypoint.sh at container start — do not edit by hand, it is"
	echo "# overwritten on every restart."
	echo ""
	echo "LogType=console"
	echo "PidFile=/run/zabbix/zabbix_proxy.pid"
	echo "SocketDir=/run/zabbix"
	echo ""
	echo "Server=${ZBX_SERVER_HOST}"
	echo "ServerPort=${ZBX_SERVER_PORT}"
	echo "Hostname=${ZBX_HOSTNAME}"
	echo ""
	# The one piece of local state this component owns (see docker/proxy/Dockerfile) — a SQLite file
	# under the db_data volume, named after the proxy's own Hostname so multiple proxies can share the
	# same image without colliding on one file, matching the official image's own default naming.
	echo "DBName=/var/lib/zabbix/db_data/${ZBX_HOSTNAME}.sqlite"
	echo ""
	echo "ExternalScripts=/var/lib/zabbix/externalscripts"
	# ProxyMode 0 = active (proxy polls the server for its config and pushes data) — the default and the
	# common case; set ZBX_PROXYMODE=1 for passive mode (server polls the proxy instead).
	if [ -n "${ZBX_PROXYMODE:-}" ]; then
		echo "ProxyMode=${ZBX_PROXYMODE}"
	fi
} > "${CONFIG_FILE}"

echo "**** Starting Zabbix proxy..."
exec zabbix_proxy --foreground -c "${CONFIG_FILE}"
