#!/bin/sh
# Zabbix web (Nginx + PHP-FPM) entrypoint [FR3.2][BR4.1][functional-spec.md ワークフロー3].
#
# Reads the same environment variable names as the official zabbix/zabbix-web-nginx-mysql image
# (DB_SERVER_HOST, DB_SERVER_PORT, MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE, ZBX_SERVER_HOST,
# ZBX_SERVER_PORT, ZBX_SERVER_NAME, PHP_TZ), generates conf/zabbix.conf.php and the PHP-FPM pool config
# from them, then runs PHP-FPM in the background and Nginx in the foreground. Both processes and this
# script run as the non-root "zabbix" user (see Dockerfile USER directive), so every file this script
# writes goes under a path that user already owns or /tmp. All logs go to stdout/stderr
# [observability-design.md] — nothing is written to a log file.

set -eu

ZABBIX_WEB_ROOT="/usr/share/zabbix"
CONFIG_FILE="${ZABBIX_WEB_ROOT}/conf/zabbix.conf.php"
FPM_CONFIG_FILE="/tmp/php-fpm-zabbix.conf"

: "${DB_SERVER_HOST:=mysql-server}"
: "${DB_SERVER_PORT:=3306}"
: "${MYSQL_USER:=zabbix}"
: "${MYSQL_DATABASE:=zabbix}"
: "${ZBX_SERVER_HOST:=zabbix-server}"
: "${ZBX_SERVER_PORT:=10051}"
: "${ZBX_SERVER_NAME:=}"
: "${PHP_TZ:=UTC}"

fail() {
	echo "**** ERROR: $1" >&2
	echo "**** Exiting..." >&2
	exit 1
}

# MYSQL_PASSWORD has no safe default (unlike the other MYSQL_* variables here, which do) — an empty DB
# password is almost never intentional, matching the official image's treatment of this variable.
if [ -z "${MYSQL_PASSWORD:-}" ]; then
	fail "MYSQL_PASSWORD is not set. This variable is mandatory for Zabbix web to connect to the database."
fi

php_escape() {
	# Escapes a value for embedding inside a single-quoted PHP string literal.
	printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g"
}

echo "**** Generating ${CONFIG_FILE} from environment variables..."

cat > "${CONFIG_FILE}" <<PHP_CONF
<?php
// Zabbix GUI configuration file.
// Generated by docker/web/entrypoint.sh at container start — do not edit by hand, it is overwritten on
// every restart. LDAP/SAML support was removed from this build, so this file carries no \$SSO block.

\$DB['TYPE']				= 'MYSQL';
\$DB['SERVER']			= '$(php_escape "${DB_SERVER_HOST}")';
\$DB['PORT']				= '$(php_escape "${DB_SERVER_PORT}")';
\$DB['DATABASE']			= '$(php_escape "${MYSQL_DATABASE}")';
\$DB['USER']				= '$(php_escape "${MYSQL_USER}")';
\$DB['PASSWORD']			= '$(php_escape "${MYSQL_PASSWORD}")';

// Schema name. Used for PostgreSQL — this project targets MySQL only [project.md Mandated].
\$DB['SCHEMA']			= '';

// DB connection is plain-text by design within the trusted internal network [security-design.md NFR1.3/1.4].
\$DB['ENCRYPTION']		= false;
\$DB['KEY_FILE']			= '';
\$DB['CERT_FILE']		= '';
\$DB['CA_FILE']			= '';
\$DB['VERIFY_HOST']		= false;
\$DB['CIPHER_LIST']		= '';

\$DB['DOUBLE_IEEE754']	= true;

\$ZBX_SERVER				= '$(php_escape "${ZBX_SERVER_HOST}")';
\$ZBX_SERVER_PORT		= '$(php_escape "${ZBX_SERVER_PORT}")';
\$ZBX_SERVER_NAME		= '$(php_escape "${ZBX_SERVER_NAME}")';

\$IMAGE_FORMAT_DEFAULT	= IMAGE_FORMAT_PNG;
PHP_CONF

echo "**** Generating PHP-FPM configuration (timezone: ${PHP_TZ})..."

cat > "${FPM_CONFIG_FILE}" <<FPM_CONF
[global]
error_log = /dev/stderr
daemonize = no

[www]
listen = 127.0.0.1:9000
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
access.log = /dev/null
catch_workers_output = yes
decorate_workers_output = no
clear_env = no
php_admin_value[date.timezone] = ${PHP_TZ}
FPM_CONF

echo "**** Starting PHP-FPM..."
php-fpm83 -y "${FPM_CONFIG_FILE}" --nodaemonize &
FPM_PID=$!

# build-and-test found nginx fails to start as the non-root "zabbix" user without -e: before it even
# reads nginx.conf's own `error_log /dev/stderr` directive, nginx tries to open its Alpine-package
# COMPILED-IN default global error log ("/var/lib/nginx/logs/error.log", owned by the "nginx" apk
# package's own user/group, not "zabbix") for early startup messages, and that open() fails with
# "Permission denied" — nginx never actually starts, and this script never notices because it puts
# nginx in the background. -e redirects that separate, pre-config-parse log destination too.
echo "**** Starting Nginx..."
nginx -e /dev/stderr -g 'daemon off;' &
NGINX_PID=$!

# This script is PID 1: forward TERM/INT to both children instead of exec'ing one of them, so a
# `podman stop`/systemd stop shuts down both nginx and PHP-FPM instead of leaving one orphaned.
term_handler() {
	echo "**** Caught signal, shutting down..."
	kill -TERM "${NGINX_PID}" 2>/dev/null || true
	kill -TERM "${FPM_PID}" 2>/dev/null || true
}
trap term_handler TERM INT

# Blocks until both background processes have exited. HEALTHCHECK (see Dockerfile) is what actually
# detects "nginx is up but not answering" or "php-fpm died" during normal operation.
wait
